#!/usr/bin/env python3
"""Local smoke test for the generic resumable batch runner.

This script does not access public websites. It creates a temporary frontier
and product store, runs one bounded pass, then resumes until the queue is empty.
"""
from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from pathlib import Path
from typing import Any

from autonomous_crawler.models.product import ProductRecord
from autonomous_crawler.runners import (
    BatchRunner,
    BatchRunnerConfig,
    ItemProcessResult,
    ProductRecordCheckpoint,
)
from autonomous_crawler.storage.frontier import URLFrontier
from autonomous_crawler.storage.product_store import ProductStore


OUTPUT_DIR = Path("dev_logs")
SUMMARY_PATH = OUTPUT_DIR / "2026-05-11_batch_runner_smoke.json"


def build_record(run_id: str, item: dict[str, Any]) -> ProductRecord:
    url = str(item["url"])
    index = int(url.rstrip("/").split("/")[-1])
    return ProductRecord(
        run_id=run_id,
        source_site="runner-smoke.local",
        source_url=url,
        canonical_url=url,
        title=f"Runner Smoke Product {index:03d}",
        highest_price=round(10.0 + index, 2),
        currency="USD",
        colors=["Black", "White"] if index % 2 == 0 else ["Blue"],
        sizes=["S", "M", "L"],
        description="Local synthetic record generated by run_batch_runner_smoke.py.",
        image_urls=[f"https://runner-smoke.local/images/{index:03d}.jpg"],
        category="runner-smoke",
        mode="synthetic_batch_runner_smoke",
    )


def run(items: int, batch_size: int, first_pass_batches: int, keep_db: bool) -> dict[str, Any]:
    OUTPUT_DIR.mkdir(exist_ok=True)
    temp_dir = Path(tempfile.mkdtemp(prefix="clm_runner_smoke_"))
    run_id = "batch-runner-smoke"
    try:
        frontier = URLFrontier(temp_dir / "frontier.sqlite3")
        product_store = ProductStore(temp_dir / "products.sqlite3")
        urls = [f"https://runner-smoke.local/products/{index}" for index in range(items)]
        add_summary = frontier.add_urls(urls, priority=10, kind="detail_page")

        def processor(item: dict[str, Any]) -> ItemProcessResult:
            return ItemProcessResult.success(records=[build_record(run_id, item)])

        checkpoint = ProductRecordCheckpoint(product_store)
        first = BatchRunner(
            frontier=frontier,
            processor=processor,
            config=BatchRunnerConfig(
                run_id=run_id,
                worker_id="runner-smoke-pass-1",
                batch_size=batch_size,
                max_batches=first_pass_batches,
            ),
            checkpoint=checkpoint,
        ).run()
        resumed = BatchRunner(
            frontier=frontier,
            processor=processor,
            config=BatchRunnerConfig(
                run_id=run_id,
                worker_id="runner-smoke-resume",
                batch_size=batch_size,
            ),
            checkpoint=checkpoint,
        ).run()

        product_stats = product_store.get_run_stats(run_id)
        summary = {
            "run_id": run_id,
            "config": {
                "items": items,
                "batch_size": batch_size,
                "first_pass_batches": first_pass_batches,
                "keep_db": keep_db,
            },
            "frontier_add": add_summary,
            "first_pass": first.as_dict(),
            "resume_pass": resumed.as_dict(),
            "final_frontier_stats": frontier.stats(),
            "product_stats": product_stats,
            "accepted": (
                product_stats["total"] == items
                and frontier.stats().get("done") == items
                and not frontier.stats().get("queued")
                and not frontier.stats().get("failed")
            ),
        }
        if keep_db:
            kept_dir = OUTPUT_DIR / "2026-05-11_batch_runner_smoke_runtime"
            if kept_dir.exists():
                shutil.rmtree(kept_dir)
            shutil.copytree(temp_dir, kept_dir)
            summary["kept_db_dir"] = str(kept_dir)
        SUMMARY_PATH.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
        return summary
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run local batch runner smoke test.")
    parser.add_argument("--items", type=int, default=25)
    parser.add_argument("--batch-size", type=int, default=5)
    parser.add_argument("--first-pass-batches", type=int, default=2)
    parser.add_argument("--keep-db", action="store_true")
    args = parser.parse_args()
    summary = run(
        items=max(1, args.items),
        batch_size=max(1, args.batch_size),
        first_pass_batches=max(1, args.first_pass_batches),
        keep_db=args.keep_db,
    )
    print(json.dumps(summary, ensure_ascii=True, indent=2))


if __name__ == "__main__":
    main()
