"""Real browser smoke test for the Playwright browser fallback path.

This test serves a tiny local SPA fixture that renders content via JavaScript,
then uses fetch_rendered_html() to verify the browser can see JS-generated DOM.

Set AUTONOMOUS_CRAWLER_RUN_BROWSER_SMOKE=1 to enable this test.
It is skipped by default so the normal test suite works without Playwright
browser binaries.
"""
from __future__ import annotations

import os
import socket
import threading
import unittest
from http.server import HTTPServer, SimpleHTTPRequestHandler
from typing import Any

# Minimal SPA HTML: renders nothing server-side, generates all content via JS.
SPA_HTML = """\
<!DOCTYPE html>
<html>
<head><title>SPA Smoke Test</title></head>
<body>
  <div id="app"></div>
  <script>
    // Simulate async SPA rendering
    setTimeout(function() {
      var el = document.getElementById("app");
      el.innerHTML = '<h1 class="js-title">JS Rendered Title</h1>'
        + '<p class="js-body">This content was generated by JavaScript after page load.</p>'
        + '<ul class="js-list">'
        + '<li data-index="1">Item Alpha</li>'
        + '<li data-index="2">Item Beta</li>'
        + '<li data-index="3">Item Gamma</li>'
        + '</ul>';
    }, 100);
  </script>
</body>
</html>
"""


def _find_free_port() -> int:
    """Find an available port on localhost."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class _SPAHandler(SimpleHTTPRequestHandler):
    """Serve the SPA fixture HTML for any request."""

    def do_GET(self) -> None:
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(SPA_HTML.encode())))
        self.end_headers()
        self.wfile.write(SPA_HTML.encode())

    def log_message(self, format: str, *args: Any) -> None:
        pass  # Suppress noisy server logs during tests


def _should_skip() -> str:
    """Return a skip reason string, or empty string if test should run."""
    if not os.environ.get("AUTONOMOUS_CRAWLER_RUN_BROWSER_SMOKE"):
        return "Set AUTONOMOUS_CRAWLER_RUN_BROWSER_SMOKE=1 to run browser smoke tests"

    try:
        from playwright.sync_api import sync_playwright
        if sync_playwright is None:
            return "playwright is installed but sync_playwright is None"
    except ImportError:
        return "playwright is not installed"

    # Quick check: can we actually launch a browser?
    try:
        from playwright.sync_api import sync_playwright as pw_fn
        with pw_fn() as pw:
            browser = pw.chromium.launch(headless=True)
            browser.close()
    except Exception as exc:
        return f"Playwright browser binaries unavailable: {exc}"

    return ""


class TestRealBrowserSPA(unittest.TestCase):
    """Smoke test: fetch_rendered_html() against a local JS-rendered page."""

    def test_browser_sees_js_rendered_content(self) -> None:
        """Playwright should see content that only exists after JS execution."""
        skip_reason = _should_skip()
        if skip_reason:
            self.skipTest(skip_reason)

        from autonomous_crawler.tools.browser_fetch import fetch_rendered_html

        # Start local SPA server
        port = _find_free_port()
        server = HTTPServer(("127.0.0.1", port), _SPAHandler)
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()

        try:
            url = f"http://127.0.0.1:{port}/"
            result = fetch_rendered_html(
                url=url,
                wait_selector=".js-title",
                wait_until="domcontentloaded",
                timeout_ms=10000,
            )

            self.assertEqual(result.status, "ok", f"Browser fetch failed: {result.error}")
            self.assertIn("JS Rendered Title", result.html)
            self.assertIn("This content was generated by JavaScript", result.html)
            self.assertIn("Item Alpha", result.html)
            self.assertIn("Item Beta", result.html)
            self.assertIn("Item Gamma", result.html)
        finally:
            server.shutdown()

    def test_browser_wait_for_selector(self) -> None:
        """wait_selector should block until the JS element appears."""
        skip_reason = _should_skip()
        if skip_reason:
            self.skipTest(skip_reason)

        from autonomous_crawler.tools.browser_fetch import fetch_rendered_html

        port = _find_free_port()
        server = HTTPServer(("127.0.0.1", port), _SPAHandler)
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()

        try:
            url = f"http://127.0.0.1:{port}/"
            result = fetch_rendered_html(
                url=url,
                wait_selector=".js-list li[data-index='3']",
                wait_until="domcontentloaded",
                timeout_ms=10000,
            )

            self.assertEqual(result.status, "ok", f"Browser fetch failed: {result.error}")
            self.assertIn("Item Gamma", result.html)
        finally:
            server.shutdown()

    def test_screenshot_capture(self) -> None:
        """Screenshot should be saved when requested."""
        skip_reason = _should_skip()
        if skip_reason:
            self.skipTest(skip_reason)

        from autonomous_crawler.tools.browser_fetch import fetch_rendered_html

        port = _find_free_port()
        server = HTTPServer(("127.0.0.1", port), _SPAHandler)
        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()

        try:
            url = f"http://127.0.0.1:{port}/"
            result = fetch_rendered_html(
                url=url,
                wait_selector=".js-title",
                timeout_ms=10000,
                screenshot=True,
            )

            self.assertEqual(result.status, "ok")
            self.assertIn("screenshots", result.screenshot_path)
        finally:
            server.shutdown()


if __name__ == "__main__":
    unittest.main()
