"""Backward-compatible re-export shim.

All ecommerce profile helpers have been merged into profile_longrun.py.
This module re-exports every public name so existing imports continue to work.
"""
from .profile_longrun import (  # noqa: F401
    EcommerceProfileCallbacks,
    absolute_urls,
    api_headers_from_profile,
    api_records_for_response,
    apply_profile_replay_diagnostics,
    as_list,
    clean_list,
    clone_json,
    completeness,
    dedupe_requests,
    dedupe_strings,
    duplicate_key_strategy_summary,
    first_text,
    hydration_product_requests,
    initial_api_json,
    initial_api_url,
    initial_requests_from_profile,
    infer_pagination_stop_reason,
    is_api_request,
    is_single_field,
    link_rule_from_profile,
    make_ecommerce_profile_callbacks,
    mapped_value,
    next_api_json,
    next_api_requests,
    next_cursor_url,
    next_offset_url,
    next_page_url,
    no_more_api_pages,
    normalize_gate_mode,
    normalize_quality_field,
    normalize_quality_policy,
    numeric_field_thresholds,
    parse_price,
    product_fields_from_html,
    product_urls_from_html,
    profile_quality_gate,
    profile_quality_summary,
    required_field_thresholds,
    response_json,
    runtime_meta_from_profile,
    selector_request,
    selector_result_values,
    selectors_for_kind,
    set_value_at_path,
    split_selector_attribute,
    value_at_path,
    with_query_params,
)
